server:
    port: 8082
spring:
    application:
        name: "servicio-turnos"
eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8761/eureka"
        registerWithEureka: true
        fetchRegistry: false
            
