server:
    port: 8081

spring:
    application:
        name: "servicio-turno"
    datasource:
        url: "jdbc:mysql://localhost:3306/cinepum?autoReconnect=true"
        username: "root"
        password: ""
        driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:    
        properties:
            hibernate:
                ddl-auto: update
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
    
eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8761/eureka"
        registerWithEureka: true
        fetchRegistry: false
